[[dependencies]]
  branch = "master"
  name = "github.com/gorilla/context"

[[dependencies]]
  branch = "master"
  name = "github.com/docker/docker/client"

[[dependencies]]
  branch = "master"
  name = "github.com/dgrijalva/jwt-go"

[[dependencies]]
  revision = "063359185d32c6b045fa171ad7033ea545864fa1"
  name = 	"github.com/satori/go.uuid"

[[dependencies]]
  branch = "master"
  name = "github.com/ghodss/yaml"

[[dependencies]]
  branch = "master"
  name = "github.com/skratchdot/open-golang/open"

[[dependencies]]
  branch = "master"
  name = "github.com/goreleaser/goreleaser"

[[dependencies]]
  branch = "master"
  name = "github.com/crackcomm/go-clitable"